Update import statements and import files that other files depend on
NREL/HOPP pull request #141
Opened 2023-07-25 19:49 UTC by ckiefer14

Import errors in hopp/simulation pythons files
base.py works in other locations

2023-07-31 22:27 UTC, jaredthomas68 requested changes

2023-08-01 01:26 UTC, ckiefer14 commented on hopp/simulation/technologies/hydrogen/electrolysis/run_h2_distributed.py
run_h2_distributed is an exact duplicate. The other location is in simulation/technologies/Electrolyzer_Models

2023-08-01 01:28 UTC, ckiefer14 commented on hopp/simulation/technologies/hydrogen/electrolysis/run_h2_power_powerElec.py
run_h2_power_powerElec is an exact duplicate. The other location is in simulation/technologies/Electrolyzer_Models.

This location was chosen over the other as this directory would be empty if these files were deleted from /Electrolyzer_Models/

2023-08-01 01:30 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/LCA_single_scenario.py
This has history associated with it

2023-08-01 01:31 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/LCA_single_scenario_ProFAST.py
This file has history with it

2023-08-01 01:32 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/h2_optimize_gf.py
History is with the file

2023-08-01 01:33 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/hopp_for_h2_floris.py
History is still there

2023-08-01 01:34 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/pipelineASME.py
History is with file

2023-08-01 01:34 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/plot_battery.py
History is with file

2023-08-01 01:35 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/plot_power_to_load.py
History is here with file

2023-08-01 01:36 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/plot_reopt_results.py
History is with file

2023-08-01 01:37 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/plot_shortfall_curtailment.py
History is with file

2023-08-01 01:38 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/run_profast_for_ammonia.py
History is with file

2023-08-01 01:39 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/run_profast_for_h2_transmission.py
History is with file

2023-08-01 01:39 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/run_profast_for_hydrogen.py
History is with file

2023-08-01 01:40 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/run_profast_for_steel.py
History is with file

2023-08-01 01:41 UTC, ckiefer14 commented on hopp/to_organize/to_organize2/run_reopt.py
History is with file

2023-08-01 19:21 UTC, merged